services:
  app:
    build:
      context: .
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on:
      - db-books
    restart: always
  db-books:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: USERS
    ports:
      - "5433:5432"